const state = { selected: null, filtered: [], saved: JSON.parse(localStorage.getItem('planeja-bncc-plans') || '[]') };
const $ = (id) => document.getElementById(id);
const normalize = (v) => (v || '').trim().toLocaleUpperCase('pt-BR');
const unique = (key) => [...new Set(BNCC_DATA.map(key).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));

function fill(selectId, values) { const el=$(selectId); values.forEach(v=>el.add(new Option(v,v))); }
fill('yearFilter', unique(r=>r.ano)); fill('termFilter', unique(r=>r.bimestre)); fill('subjectFilter', unique(r=>r.componente)); fill('axisFilter', unique(r=>r.eixo));
$('statMatches').textContent = BNCC_DATA.length;

function filtered(){ const y=$('yearFilter').value,t=$('termFilter').value,s=$('subjectFilter').value,a=$('axisFilter').value; return BNCC_DATA.filter(r=>(!y||r.ano===y)&&(!t||r.bimestre===t)&&(!s||r.componente===s)&&(!a||r.eixo===a)); }
function renderMatches(){ state.filtered=filtered(); $('resultCount').textContent=`${state.filtered.length} integração(ões) encontrada(s)`; const list=$('matchList'); if(!state.filtered.length){list.innerHTML='<div class="no-results">Nenhuma integração encontrada com estes filtros. Tente ampliar a busca.</div>';return;} list.innerHTML=state.filtered.slice(0,24).map((r,i)=>`<button class="match ${state.selected===r?'selected':''}" data-index="${i}"><div class="chips"><span class="chip">${r.ano} · ${r.bimestre}</span><span class="chip orange">${r.eixo}</span></div><h3>${r.componente} · ${r.habEspecifica} + ${r.habComputacao}</h3><p>${r.objeto || r.descricaoEspecifica}</p></button>`).join(''); list.querySelectorAll('.match').forEach(el=>el.onclick=()=>choose(state.filtered[Number(el.dataset.index)])); }
function choose(row){state.selected=row; $('planner').classList.remove('hidden'); renderMatches(); $('planner').scrollIntoView({behavior:'smooth',block:'start'}); generate();}
function guidance(r, res){const tema=$('theme').value.trim()||'um contexto próximo da turma'; const digital=res==='unplugged'?'cartões, fichas, fluxograma em papel e materiais da sala':res==='hybrid'?'registros em papel e, quando possível, uma ferramenta digital simples':'dispositivos com uma ferramenta de criação, tabela ou programação visual'; const action={ 'Pensamento Computacional':'decompor o desafio, identificar padrões e registrar uma sequência de decisões', 'Mundo Digital':'investigar como a informação é criada, armazenada, comunicada ou protegida', 'Cultura Digital':'analisar criticamente os impactos, usos e escolhas no ambiente digital'}[r.eixo]||'investigar e resolver o desafio de forma organizada'; return {tema,digital,action};}
function generate(){const r=state.selected;if(!r)return;const duration=$('duration').value,res=$('resources').value,c=$('className').value.trim(),g=guidance(r,res);const title=`${r.componente}: ${r.objeto || 'integração curricular'}`; $('planOutput').innerHTML=`<div class="plan-title"><p class="eyebrow">PLANO INTEGRADO ${c?`· ${c.toUpperCase()}`:''}</p><h2>${title}</h2><div class="meta"><span>${r.ano}</span><span>${r.bimestre}</span><span>${duration}</span><span>${res==='unplugged'?'Sem dispositivos':res==='hybrid'?'Híbrido':'Com dispositivos'}</span></div></div><div class="plan-grid"><section><h3>HABILIDADE DO COMPONENTE</h3><p><strong>${r.habEspecifica}</strong> — ${r.descricaoEspecifica}</p></section><section><h3>BNCC COMPUTAÇÃO</h3><p><strong>${r.habComputacao}</strong> · ${r.eixo}<br>${r.descricaoComputacao}</p></section><section class="full"><h3>OBJETIVO INTEGRADO</h3><p>Ao investigar <strong>${g.tema}</strong>, os estudantes desenvolverão a habilidade de ${r.componente.toLowerCase()} relacionada a <strong>${r.objeto || 'este objeto de conhecimento'}</strong> e, simultaneamente, irão ${g.action}.</p></section><section><h3>PROPOSTA DE ATIVIDADE</h3><ul><li><strong>Disparador:</strong> apresente uma situação ou pergunta ligada a ${g.tema} e recupere conhecimentos prévios.</li><li><strong>Investigação:</strong> em grupos, analisem exemplos e dados relacionados ao objeto de conhecimento.</li><li><strong>Estratégia computacional:</strong> organizem o problema em etapas, critérios, informações e decisões.</li><li><strong>Produção:</strong> criem uma explicação, modelo, registro ou solução usando ${g.digital}.</li><li><strong>Socialização:</strong> comparem soluções, testem critérios e revisem o produto.</li></ul></section><section><h3>EVIDÊNCIA DE APRENDIZAGEM</h3><p>Um produto que explicite o conhecimento do componente curricular e a estratégia computacional utilizada: mapa de ideias, fluxograma, tabela, algoritmo, apresentação comentada ou protótipo.</p><h3>MEDIAÇÃO DO PROFESSOR</h3><p>Pergunte: “Que informações são relevantes?”, “Como vocês decidiram?”, “O que acontece se mudarmos esta condição?” e “Como sabemos que a solução funciona?”</p></section><section class="full"><h3>RUBRICA DE AVALIAÇÃO</h3><table class="rubric"><thead><tr><th>Critério</th><th>Evidência esperada</th></tr></thead><tbody><tr><td>Habilidade do componente</td><td>Aplica ${r.habEspecifica} com precisão ao analisar ou produzir.</td></tr><tr><td>Habilidade computacional</td><td>Mobiliza ${r.habComputacao} para organizar, investigar, modelar ou resolver.</td></tr><tr><td>Justificativa e revisão</td><td>Explica escolhas, testa a proposta e melhora o produto a partir de evidências.</td></tr></tbody></table></section></div>`;}
function renderSaved(){const out=$('savedPlans'); if(!state.saved.length){out.innerHTML='<p class="empty">Os planos que você salvar aparecerão aqui neste navegador.</p>';return;}out.innerHTML=state.saved.map((p,i)=>`<article class="saved-card"><span class="chip">${p.ano} · ${p.bimestre}</span><h3>${p.title}</h3><p>${p.componente} · ${p.habComputacao}</p><button class="button ghost" data-saved="${i}">Abrir</button></article>`).join('');out.querySelectorAll('[data-saved]').forEach(b=>b.onclick=()=>{state.selected=BNCC_DATA.find(r=>r.id===state.saved[Number(b.dataset.saved)].id);$('planner').classList.remove('hidden');generate();$('planner').scrollIntoView({behavior:'smooth'});});}
function coverage(){const total=BNCC_DATA.length;const c={};BNCC_DATA.forEach(r=>c[r.eixo]=(c[r.eixo]||0)+1);$('coverageCards').innerHTML=Object.entries(c).map(([axis,count])=>`<article class="coverage-card"><strong>${count}</strong><span>${axis}<br>${Math.round(count/total*100)}% das integrações</span></article>`).join('');}
['yearFilter','termFilter','subjectFilter','axisFilter'].forEach(id=>$(id).onchange=renderMatches);$('clearFilters').onclick=()=>{['yearFilter','termFilter','subjectFilter','axisFilter'].forEach(id=>$(id).value='');renderMatches();};['duration','resources','className','theme'].forEach(id=>$(id).oninput=generate);$('generatePlan').onclick=generate;$('printPlan').onclick=()=>{if(!state.selected){alert('Escolha uma articulação antes de imprimir.');return;}window.print();};$('copyPlan').onclick=async()=>{if(!state.selected)return;await navigator.clipboard.writeText($('planOutput').innerText);$('copyPlan').textContent='Copiado!';setTimeout(()=>$('copyPlan').textContent='Copiar texto',1600)};$('savePlan').onclick=()=>{if(!state.selected)return;const r=state.selected;state.saved.unshift({id:r.id,title:r.objeto||r.descricaoEspecifica.slice(0,60),ano:r.ano,bimestre:r.bimestre,componente:r.componente,habComputacao:r.habComputacao});localStorage.setItem('planeja-bncc-plans',JSON.stringify(state.saved));renderSaved();$('biblioteca').scrollIntoView({behavior:'smooth'});};
renderMatches();coverage();renderSaved();
